services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run dev -- --host
    volumes:
      # - ./src:/src
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
